### ISSUE TITLE
support GRPC

### ISSUE THREAD

**Issue by markphelps** [flipt-io/reverst#3]
It should be possible to support GRPC over QUIC I think

edit: maybe not easily, looking at https://github.com/grpc/grpc/issues/19126

**Comment by GeorgeMac** [comment]
Mmm yeah I can hear the crickets in that GH issue, but would love to explore this more deeply!
I see someone in there just did some dialer magic that worked for them:
https://github.com/grpc/grpc/issues/19126#issuecomment-1255911889

Maybe there is a little hackery we can do here to get something together.
